name: Publish npm Package

on:
  push:
    branches:
      - main       # Publish juga bisa trigger lewat tag
    tags:
      - 'v*.*.*'   # Hanya untuk versi semantik seperti v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      # 3. Install dependencies
      - run: npm ci

      # 4. Run tests
      - run: npm test

      # 5. Build package
      - run: npm run build

      # 6. Publish to npm (hanya jika tag baru)
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
